name = "omni-pos"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "omni-pos"
database_id = "a50fddea-e22f-419c-afb8-6c40464e4a6a"

[assets]
directory = "./dist"