pages_build_output_dir = "dist"
compatibility_date = "2024-04-01"

[[d1_databases]]
binding = "DB" 
database_name = "pos"
database_id = "5657e25b-bcdb-4fb8-9a2b-4b1f80259e9f"

[vars]
# Add project-specific variables here